-- 风险评估报告表
CREATE TABLE IF NOT EXISTS `risk_report` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `report_id` VARCHAR(50) NOT NULL COMMENT '报告编号，如：RPT20260122001',
    `user_id` BIGINT NOT NULL COMMENT '用户ID',
    `conversation_id` BIGINT NOT NULL COMMENT '会话ID',
    `our_side` VARCHAR(200) NOT NULL COMMENT '我方当事人',
    `our_identity` VARCHAR(50) NOT NULL COMMENT '我方身份（原告/被告/申请人/被申请人/债权人/债务人等）',
    `other_party` VARCHAR(200) NOT NULL COMMENT '对方当事人',
    `other_identity` VARCHAR(50) NOT NULL COMMENT '对方身份',
    `case_reason` VARCHAR(100) NOT NULL COMMENT '案由',
    `core_demand` TEXT NOT NULL COMMENT '核心诉求',
    `basic_facts` TEXT NOT NULL COMMENT '基本事实',
    `available_core_evidence` TEXT NOT NULL COMMENT '现有核心证据',
    `report_date` VARCHAR(50) NOT NULL COMMENT '报告日期，格式：YYYY年MM月DD日',
    `overall_risk_level` VARCHAR(50) NOT NULL COMMENT '综合风险等级（较低风险/中等风险/较高风险）',
    `overall_risk_score` INT NOT NULL COMMENT '风险评分（10-100分）',
    `overall_risk_score_reason` TEXT COMMENT '风险评分原因',
    `advantages_opportunity_analysis` TEXT COMMENT '优势与机会分析',
    `risk_challenge_alert` TEXT COMMENT '风险挑战提示',
    `risk_point` VARCHAR(500) COMMENT '风险点简述',
    `action_suggestions_subsequent_strategies` TEXT COMMENT '行动建议与后续策略',
    `full_report_content` LONGTEXT COMMENT '完整报告内容（Markdown格式）',
    `report_file_path` VARCHAR(500) COMMENT '报告文件路径（PDF）',
    `download_link` VARCHAR(500) COMMENT '下载链接',
    `link_expire_time` DATETIME COMMENT '下载链接过期时间',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_report_id` (`report_id`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_conversation_id` (`conversation_id`),
    KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='风险评估报告表';
